// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Z0EQKsyUp9ZpUNOWyXuchmz7L1ZtB8o',
    appId: '1:92595988023:web:cf91f5089920f6ace8c1b2',
    messagingSenderId: '92595988023',
    projectId: 'like-app-37fcf',
    authDomain: 'like-app-37fcf.firebaseapp.com',
    storageBucket: 'like-app-37fcf.appspot.com',
    measurementId: 'G-7QTTHGP95G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlWdURMyP5WKu6P_HeME_sHWh_GG9xX4Y',
    appId: '1:92595988023:android:00cd3981062990bde8c1b2',
    messagingSenderId: '92595988023',
    projectId: 'like-app-37fcf',
    storageBucket: 'like-app-37fcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfOYuzdKRvQnfPeR5HOCQy_w-JH7V9E0',
    appId: '1:92595988023:ios:d146dd76db11e18fe8c1b2',
    messagingSenderId: '92595988023',
    projectId: 'like-app-37fcf',
    storageBucket: 'like-app-37fcf.appspot.com',
    iosClientId: '92595988023-sti1vv938ijk3eqpa1j8dm68qnc79rgh.apps.googleusercontent.com',
    iosBundleId: 'com.nurs.likeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHfOYuzdKRvQnfPeR5HOCQy_w-JH7V9E0',
    appId: '1:92595988023:ios:dbb4d324c83b7dfde8c1b2',
    messagingSenderId: '92595988023',
    projectId: 'like-app-37fcf',
    storageBucket: 'like-app-37fcf.appspot.com',
    iosClientId: '92595988023-ieoevheal0shvftppbmhd7m394jmvfos.apps.googleusercontent.com',
    iosBundleId: 'com.example.likeApp',
  );
}
