// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjf1Zb_EUJw8wjvnQNSkee7Q0unyk-IbY',
    appId: '1:477048858360:web:87219ed5a2e836be487d0d',
    messagingSenderId: '477048858360',
    projectId: 'flutter-storage-beedd',
    authDomain: 'flutter-storage-beedd.firebaseapp.com',
    storageBucket: 'flutter-storage-beedd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTk0BKL6HKcNQUU1lLxyetjBpFUcGzyIU',
    appId: '1:477048858360:android:756fd0e90ffd9002487d0d',
    messagingSenderId: '477048858360',
    projectId: 'flutter-storage-beedd',
    storageBucket: 'flutter-storage-beedd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnocAmv5_VIAVXb4Pt0OwWi2VK_zhA1qI',
    appId: '1:477048858360:ios:ff46fe22950b224f487d0d',
    messagingSenderId: '477048858360',
    projectId: 'flutter-storage-beedd',
    storageBucket: 'flutter-storage-beedd.appspot.com',
    iosClientId: '477048858360-qb7dvlnjja2eseaodkcdhg0ou25g7fjg.apps.googleusercontent.com',
    iosBundleId: 'com.nurs.storageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnocAmv5_VIAVXb4Pt0OwWi2VK_zhA1qI',
    appId: '1:477048858360:ios:498d76196aaf6c62487d0d',
    messagingSenderId: '477048858360',
    projectId: 'flutter-storage-beedd',
    storageBucket: 'flutter-storage-beedd.appspot.com',
    iosClientId: '477048858360-ropnk57sjkklfhs516sil1l7vsk0o7rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageApp',
  );
}
