// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdWZKcxAYyAwlB3XlghtXpYXeZUsNFYs',
    appId: '1:404001860404:web:7c9d906a6c36142ef7d361',
    messagingSenderId: '404001860404',
    projectId: 'flutterapp-89b4d',
    authDomain: 'flutterapp-89b4d.firebaseapp.com',
    storageBucket: 'flutterapp-89b4d.appspot.com',
    measurementId: 'G-X8F3V1S6BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64uCLwJoo-vxPeSHc7oQvVJ5JsQD6IqE',
    appId: '1:404001860404:android:55047bf4020b5713f7d361',
    messagingSenderId: '404001860404',
    projectId: 'flutterapp-89b4d',
    storageBucket: 'flutterapp-89b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5SPHojlAlM6SjNCYKf11ELJWQJiCxmHA',
    appId: '1:404001860404:ios:8afbcef15e80ad61f7d361',
    messagingSenderId: '404001860404',
    projectId: 'flutterapp-89b4d',
    storageBucket: 'flutterapp-89b4d.appspot.com',
    iosClientId: '404001860404-b9rr49iniorgvcpdr4kln6fcspl1dl8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5SPHojlAlM6SjNCYKf11ELJWQJiCxmHA',
    appId: '1:404001860404:ios:8afbcef15e80ad61f7d361',
    messagingSenderId: '404001860404',
    projectId: 'flutterapp-89b4d',
    storageBucket: 'flutterapp-89b4d.appspot.com',
    iosClientId: '404001860404-b9rr49iniorgvcpdr4kln6fcspl1dl8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireflutter',
  );
}
