// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAatxajs6WMDsRs8pd5fY_KNhGmcWtloxw',
    appId: '1:24064851646:web:7b441a8a65c156c8c6a8ef',
    messagingSenderId: '24064851646',
    projectId: 'my-form-app-9c9bb',
    authDomain: 'my-form-app-9c9bb.firebaseapp.com',
    storageBucket: 'my-form-app-9c9bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBTbEX05PvIZ-sfdeynRt35B_-Xf1-r5I',
    appId: '1:24064851646:android:48bc0805f4c2c1fdc6a8ef',
    messagingSenderId: '24064851646',
    projectId: 'my-form-app-9c9bb',
    storageBucket: 'my-form-app-9c9bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDDlhMcy1V_WQpueNk94iiyh4ab9tSKZk',
    appId: '1:24064851646:ios:4b2363b12c74cc4ec6a8ef',
    messagingSenderId: '24064851646',
    projectId: 'my-form-app-9c9bb',
    storageBucket: 'my-form-app-9c9bb.appspot.com',
    iosClientId: '24064851646-dmmfpqf0rmupdija6lasanv9ta9fh8um.apps.googleusercontent.com',
    iosBundleId: 'com.nurs.formApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDDlhMcy1V_WQpueNk94iiyh4ab9tSKZk',
    appId: '1:24064851646:ios:5410e0e52b2d5c07c6a8ef',
    messagingSenderId: '24064851646',
    projectId: 'my-form-app-9c9bb',
    storageBucket: 'my-form-app-9c9bb.appspot.com',
    iosClientId: '24064851646-rrc2tci9rc0e05h646bav2efa216sjfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.formApp',
  );
}
