// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm50Ql_CI-g0IV0Xi0nRlJjF9P9f-OwAM',
    appId: '1:342639587026:web:8831a9e81ea0102fbe470b',
    messagingSenderId: '342639587026',
    projectId: 'storage-app-11a74',
    authDomain: 'storage-app-11a74.firebaseapp.com',
    storageBucket: 'storage-app-11a74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0YyX_kv61_fD9rbfBnURjZ1z-3JPHVDY',
    appId: '1:342639587026:android:4c7868919b169c1abe470b',
    messagingSenderId: '342639587026',
    projectId: 'storage-app-11a74',
    storageBucket: 'storage-app-11a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VDyJgGB85P87CDGtJpr1CFUY8kSuT3Y',
    appId: '1:342639587026:ios:955430b7b2dfa464be470b',
    messagingSenderId: '342639587026',
    projectId: 'storage-app-11a74',
    storageBucket: 'storage-app-11a74.appspot.com',
    iosClientId: '342639587026-anjhr2dr6ltsgorkk2ne1vin10ji8ud1.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VDyJgGB85P87CDGtJpr1CFUY8kSuT3Y',
    appId: '1:342639587026:ios:955430b7b2dfa464be470b',
    messagingSenderId: '342639587026',
    projectId: 'storage-app-11a74',
    storageBucket: 'storage-app-11a74.appspot.com',
    iosClientId: '342639587026-anjhr2dr6ltsgorkk2ne1vin10ji8ud1.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageApp',
  );
}
