// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Qv7gDGev2hq-hhNWKoQ_TNdzR88w2ZY',
    appId: '1:606310247947:web:eb34da5e73676ddc9d610e',
    messagingSenderId: '606310247947',
    projectId: 'counter-app-86d9c',
    authDomain: 'counter-app-86d9c.firebaseapp.com',
    storageBucket: 'counter-app-86d9c.appspot.com',
    measurementId: 'G-1N5WWM6LNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRyIgHTsPIlUSEl4jR1JGZ84Nx57ScxNk',
    appId: '1:606310247947:android:74356948362dc9109d610e',
    messagingSenderId: '606310247947',
    projectId: 'counter-app-86d9c',
    storageBucket: 'counter-app-86d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHKWefZEyGdZoEcbcizHstu1j2RlVPRE',
    appId: '1:606310247947:ios:37f71b29c5d06fee9d610e',
    messagingSenderId: '606310247947',
    projectId: 'counter-app-86d9c',
    storageBucket: 'counter-app-86d9c.appspot.com',
    iosClientId: '606310247947-iusi7k6dat27j9lcmfu7iqv0oemc6ge6.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFHKWefZEyGdZoEcbcizHstu1j2RlVPRE',
    appId: '1:606310247947:ios:37f71b29c5d06fee9d610e',
    messagingSenderId: '606310247947',
    projectId: 'counter-app-86d9c',
    storageBucket: 'counter-app-86d9c.appspot.com',
    iosClientId: '606310247947-iusi7k6dat27j9lcmfu7iqv0oemc6ge6.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterApp',
  );
}
