// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsC8AE1z81-TAeb0qsg3AMUnhGUYZd9k',
    appId: '1:398440786800:web:fdb53c262eb7a5d0db3db5',
    messagingSenderId: '398440786800',
    projectId: 'fluttercloudfunctions-6a3e3',
    authDomain: 'fluttercloudfunctions-6a3e3.firebaseapp.com',
    storageBucket: 'fluttercloudfunctions-6a3e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKnJF1L_ip_-RmQoTvEObm0M3l0_uhFY',
    appId: '1:398440786800:android:49f948ee46632baddb3db5',
    messagingSenderId: '398440786800',
    projectId: 'fluttercloudfunctions-6a3e3',
    storageBucket: 'fluttercloudfunctions-6a3e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOjakIFHjffmRTr6v6hr0Gk9M9p1b1dUA',
    appId: '1:398440786800:ios:f1724d82f9014499db3db5',
    messagingSenderId: '398440786800',
    projectId: 'fluttercloudfunctions-6a3e3',
    storageBucket: 'fluttercloudfunctions-6a3e3.appspot.com',
    iosClientId: '398440786800-d1032p6ovv92f7ovfcseguv63ojov1iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCloudFunctions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOjakIFHjffmRTr6v6hr0Gk9M9p1b1dUA',
    appId: '1:398440786800:ios:f1724d82f9014499db3db5',
    messagingSenderId: '398440786800',
    projectId: 'fluttercloudfunctions-6a3e3',
    storageBucket: 'fluttercloudfunctions-6a3e3.appspot.com',
    iosClientId: '398440786800-d1032p6ovv92f7ovfcseguv63ojov1iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCloudFunctions',
  );
}
