// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOjPP2UMIG2oqID-uKH0Y8qjJIZbkZ0o',
    appId: '1:614902256628:web:fbd45420dd96328e6adfa1',
    messagingSenderId: '614902256628',
    projectId: 'my-app-57bd0',
    authDomain: 'my-app-57bd0.firebaseapp.com',
    storageBucket: 'my-app-57bd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9BWrZ941lnXhfGWRyjANkJlsaQpTgek',
    appId: '1:614902256628:android:e8177992ff40dd976adfa1',
    messagingSenderId: '614902256628',
    projectId: 'my-app-57bd0',
    storageBucket: 'my-app-57bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rUUNhezvodDhzquCfkQMj52dhq_hlX4',
    appId: '1:614902256628:ios:71f07e96428340536adfa1',
    messagingSenderId: '614902256628',
    projectId: 'my-app-57bd0',
    storageBucket: 'my-app-57bd0.appspot.com',
    iosClientId: '614902256628-84giup0alivf36bsa3jj8rhi0u69iqg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8rUUNhezvodDhzquCfkQMj52dhq_hlX4',
    appId: '1:614902256628:ios:71f07e96428340536adfa1',
    messagingSenderId: '614902256628',
    projectId: 'my-app-57bd0',
    storageBucket: 'my-app-57bd0.appspot.com',
    iosClientId: '614902256628-84giup0alivf36bsa3jj8rhi0u69iqg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
