// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjKyyapjraueQUz9Msfod2DUPQGJ4Bz4',
    appId: '1:577034647284:web:fba93da55555c3c07190a1',
    messagingSenderId: '577034647284',
    projectId: 'my-poll-1c2e6',
    authDomain: 'my-poll-1c2e6.firebaseapp.com',
    storageBucket: 'my-poll-1c2e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX04T0RzHmGDu5SO1tapLMRgbEhX2rsuM',
    appId: '1:577034647284:android:9cde34eb631847e67190a1',
    messagingSenderId: '577034647284',
    projectId: 'my-poll-1c2e6',
    storageBucket: 'my-poll-1c2e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqVg66tQYI5TieoYiBekY27sL-_a8Oq4',
    appId: '1:577034647284:ios:945a8e31c4f956937190a1',
    messagingSenderId: '577034647284',
    projectId: 'my-poll-1c2e6',
    storageBucket: 'my-poll-1c2e6.appspot.com',
    iosClientId: '577034647284-9rut6jll9hvg76btl2pkeme35320aks5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPoll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqVg66tQYI5TieoYiBekY27sL-_a8Oq4',
    appId: '1:577034647284:ios:945a8e31c4f956937190a1',
    messagingSenderId: '577034647284',
    projectId: 'my-poll-1c2e6',
    storageBucket: 'my-poll-1c2e6.appspot.com',
    iosClientId: '577034647284-9rut6jll9hvg76btl2pkeme35320aks5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPoll',
  );
}
